name: Docs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,5 * * *'
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-24.04
    name: spelling
    steps:
      - name: Eco-CI Init
        uses: green-coding-solutions/eco-ci-energy-estimation@main
        with:
          task: start-measurement

      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: 'docs/requirements.txt'
      - run: python -m pip install -r docs/requirements.txt
      - name: Build docs
        run: |
          cd docs
          sphinx-build -b spelling -n -q -W -d _build/doctrees -D language=en_US -j auto . _build/spelling

      - name: Eco-CI Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@main
        with:
          task: get-measurement
          label: 'docs'

      - name: Eco-CI Results
        uses: green-coding-solutions/eco-ci-energy-estimation@main
        with:
          task: display-results

  blacken-docs:
    runs-on: ubuntu-latest
    name: blacken-docs
    steps:
      - name: Eco-CI Init
        uses: green-coding-solutions/eco-ci-energy-estimation@main
        with:
          task: start-measurement

      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - run: python -m pip install blacken-docs
      - name: Build docs
        run: |
          cd docs
          make black
          RESULT=`cat _build/black/output.txt`
          if [ "$RESULT" -gt 0 ]; then
              echo "ðŸ’¥ ðŸ“¢ Code blocks in documentation must be reformatted with blacken-docs ðŸ“¢ ðŸ’¥"
          fi;
          exit $RESULT

      - name: Eco-CI Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@main
        with:
          task: get-measurement
          label: 'blacken-docs'

      - name: Eco-CI Results
        uses: green-coding-solutions/eco-ci-energy-estimation@main
        with:
          task: display-results

  lint-docs:
    runs-on: ubuntu-latest
    name: lint-docs
    steps:
      - name: Eco-CI Init
        uses: green-coding-solutions/eco-ci-energy-estimation@main
        with:
          task: start-measurement

      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - run: python -m pip install sphinx-lint
      - name: Build docs
        run: |
          cd docs
          make lint

      - name: Eco-CI Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@main
        with:
          task: get-measurement
          label: 'lint docs'

      - name: Eco-CI Results
        uses: green-coding-solutions/eco-ci-energy-estimation@main
        with:
          task: display-results

